import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

// Utility to parse basic HTML from Rich Text Editor to TextRuns
const htmlToTextRuns = (htmlString) => {
    if (!htmlString) return [];
    
    // Extremely basic parser for the simple HTML generated by our RichTextEditor
    // It strips tags and replaces li with bullet points
    const text = htmlString
        .replace(/<li>/g, '• ')
        .replace(/<\/li>/g, '\n')
        .replace(/<ul>/g, '')
        .replace(/<\/ul>/g, '')
        .replace(/<p>/g, '')
        .replace(/<\/p>/g, '\n')
        .replace(/<br>/g, '\n')
        .replace(/<[^>]+>/g, ''); // Strip remaining tags
        
    const lines = text.split('\n').filter(l => l.trim() !== '');
    
    return lines.map(line => new TextRun({
        text: line,
        break: 1,
    }));
};

export const generateDocx = async (resumeInfo) => {
    if (!resumeInfo) return;

    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                // Header (Name and Details)
                new Paragraph({
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({
                            text: `${resumeInfo?.firstName || ''} ${resumeInfo?.lastName || ''}`,
                            bold: true,
                            size: 32, // Half-points (16pt)
                        }),
                    ],
                }),
                new Paragraph({
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({
                            text: resumeInfo?.jobTitle || '',
                            size: 24,
                            color: "666666",
                        }),
                    ],
                }),
                new Paragraph({
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({
                            text: [resumeInfo?.address, resumeInfo?.phone, resumeInfo?.email].filter(Boolean).join(' | '),
                            size: 20,
                        }),
                    ],
                    spacing: { after: 200 },
                }),

                // Summary
                ...(resumeInfo?.summery ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Professional Summary', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 200, after: 100 },
                    }),
                    new Paragraph({
                        children: [new TextRun({ text: resumeInfo.summery })],
                    })
                ] : []),

                // Experience
                ...(resumeInfo?.Experience?.length > 0 ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Experience', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 300, after: 100 },
                    }),
                    ...resumeInfo.Experience.flatMap(exp => [
                        new Paragraph({
                            children: [
                                new TextRun({ text: exp.title, bold: true }),
                                new TextRun({ text: ` | ${exp.companyName}`, italics: true }),
                            ],
                            spacing: { before: 100 },
                        }),
                        new Paragraph({
                            children: [
                                new TextRun({ text: `${exp.city}, ${exp.state} | ${exp.startDate} - ${exp.endDate || 'Present'}` }),
                            ],
                        }),
                        new Paragraph({
                            children: htmlToTextRuns(exp.workSummery),
                        }),
                    ])
                ] : []),

                // Education
                ...(resumeInfo?.education?.length > 0 ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Education', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 300, after: 100 },
                    }),
                    ...resumeInfo.education.flatMap(edu => [
                        new Paragraph({
                            children: [
                                new TextRun({ text: edu.universityName, bold: true }),
                            ],
                            spacing: { before: 100 },
                        }),
                        new Paragraph({
                            children: [
                                new TextRun({ text: `${edu.degree} in ${edu.major} | ${edu.startDate} - ${edu.endDate}` }),
                            ],
                        }),
                        new Paragraph({
                            children: [new TextRun({ text: edu.description })],
                        }),
                    ])
                ] : []),

                // Skills
                ...(resumeInfo?.skills?.length > 0 ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Skills', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 300, after: 100 },
                    }),
                    new Paragraph({
                        children: [
                            new TextRun({ text: resumeInfo.skills.map(s => s.name).join(', ') })
                        ],
                    })
                ] : []),
            ],
        }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `${resumeInfo?.firstName || 'Resume'}_ATS.docx`);
};
