import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';
import { mapResumeInfoToTemplateData, validateTemplateData } from '@/lib/templateDataMapper';
import { toast } from 'sonner';

// Utility to parse basic HTML from Rich Text Editor to TextRuns
const htmlToTextRuns = (htmlString) => {
    if (!htmlString) return [];
    
    // Extremely basic parser for the simple HTML generated by our RichTextEditor
    // It strips tags and replaces li with bullet points
    const text = htmlString
        .replace(/<li>/g, '• ')
        .replace(/<\/li>/g, '\n')
        .replace(/<ul>/g, '')
        .replace(/<\/ul>/g, '')
        .replace(/<p>/g, '')
        .replace(/<\/p>/g, '\n')
        .replace(/<br>/g, '\n')
        .replace(/<[^>]+>/g, ''); // Strip remaining tags
        
    const lines = text.split('\n').filter(l => l.trim() !== '');
    
    return lines.map(line => new TextRun({
        text: line,
        break: 1,
    }));
};

export const generateDocx = async (resumeInfo) => {
    if (!resumeInfo) return;

    const mappedData = mapResumeInfoToTemplateData(resumeInfo);
    validateTemplateData(mappedData);

    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                // Header (Name and Details)
                new Paragraph({
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({
                            text: mappedData.personal_info.full_name || 'Your Name',
                            bold: true,
                            size: 32, // Half-points (16pt)
                        }),
                    ],
                }),
                new Paragraph({
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({
                            text: mappedData.personal_info.profession || '',
                            size: 24,
                            color: "666666",
                        }),
                    ],
                }),
                new Paragraph({
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({
                            text: [mappedData.personal_info.location, mappedData.personal_info.phone, mappedData.personal_info.email, mappedData.personal_info.linkedin].filter(Boolean).join(' | '),
                            size: 20,
                        }),
                    ],
                    spacing: { after: 200 },
                }),

                // Summary
                ...(mappedData.professional_summary ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Professional Summary', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 200, after: 100 },
                    }),
                    new Paragraph({
                        children: [new TextRun({ text: mappedData.professional_summary })],
                    })
                ] : []),

                // Experience
                ...(mappedData.experience?.length > 0 ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Experience', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 300, after: 100 },
                    }),
                    ...mappedData.experience.flatMap(exp => [
                        new Paragraph({
                            children: [
                                new TextRun({ text: exp.position, bold: true }),
                                new TextRun({ text: ` | ${exp.company}`, italics: true }),
                            ],
                            spacing: { before: 100 },
                        }),
                        new Paragraph({
                            children: [
                                new TextRun({ text: [exp.city, exp.state].filter(Boolean).join(', ') + ` | ${exp.start_date} - ${exp.is_current ? 'Present' : exp.end_date}` }),
                            ],
                        }),
                        new Paragraph({
                            children: htmlToTextRuns(exp.description),
                        }),
                    ])
                ] : []),

                // Education
                ...(mappedData.education?.length > 0 ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Education', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 300, after: 100 },
                    }),
                    ...mappedData.education.flatMap(edu => [
                        new Paragraph({
                            children: [
                                new TextRun({ text: edu.institution, bold: true }),
                            ],
                            spacing: { before: 100 },
                        }),
                        new Paragraph({
                            children: [
                                new TextRun({ text: `${edu.degree} ${edu.field ? 'in ' + edu.field : ''} | ${edu.graduation_date}` }),
                            ],
                        }),
                        new Paragraph({
                            children: [new TextRun({ text: edu.description })],
                        }),
                    ])
                ] : []),

                // Skills
                ...(mappedData.skills?.length > 0 ? [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_2,
                        children: [new TextRun({ text: 'Skills', color: resumeInfo?.themeColor?.replace('#','') || "000000" })],
                        spacing: { before: 300, after: 100 },
                    }),
                    new Paragraph({
                        children: [
                            new TextRun({ text: mappedData.skills.join(', ') })
                        ],
                    })
                ] : []),
            ],
        }],
    });

    try {
        const blob = await Packer.toBlob(doc);
        saveAs(blob, `${mappedData.personal_info.full_name || 'Resume'}_ATS.docx`);
    } catch (error) {
        toast.error('Failed to generate Word document. Please try again.');
    }
};
