/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#9f5bff",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "on-secondary-fixed": "#270058",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#3cdae2",
        "on-secondary-container": "#faf1ff",
        "surface-container-low": "#f6f3f2",
        "secondary-container": "#8b3dff",
        "stitch-primary": "#00696e",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "primary-container": "#00c4cc",
        "surface-tint": "#00696e",
        "outline": "#6c7a7a",
        "surface-container-high": "#eae7e7",
        "inverse-surface": "#303030",
        "tertiary-fixed-dim": "#ffaed8",
        "on-background": "#1b1b1c",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "on-primary": "#ffffff",
        "surface-dim": "#dcd9d9",
        "surface": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#004c4f",
        "surface-bright": "#fcf9f8",
        "primary-fixed": "#63f7ff",
        "secondary-fixed": "#ebdcff",
        "on-secondary-fixed-variant": "#5d00c2",
        "tertiary": "#ad1d7f",
        "tertiary-container": "#ff8acc",
        "on-tertiary-fixed-variant": "#890063",
        "on-tertiary-container": "#84005f",
        "stitch-background": "#fcf9f8",
        "on-tertiary-fixed": "#3c0029",
        "on-surface-variant": "#3c494a",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1b1c",
        "outline-variant": "#bbc9ca",
        "on-primary-fixed-variant": "#004f53",
        "on-primary-fixed": "#002021",
        "stitch-secondary": "#710fe5",
        "secondary-fixed-dim": "#d4bbff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffd8e9",
        "surface-container": "#f0eded",
        "inverse-primary": "#3cdae2"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "body-md": ["Inter"]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "sm": "8px",
        "xl": "48px",
        "base": "4px",
        "xs": "4px",
        "gutter": "16px",
        "md": "16px",
        "container-margin": "24px",
        "lg": "24px"
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}